name: DiagnoBot CI

on:
  push:
    branches:
      - main
      - 'DIABOT-**'
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yml
    with:
      WORKSPACE: ${{ github.ref_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
