name: Docker build workflow

on:
  workflow_call:
    inputs:
      WORKSPACE:
        type: string
        required: true

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/diagnobot:${{ inputs.WORKSPACE }}

      - name: Pull and run the Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/diagnobot:${{ inputs.WORKSPACE }}
          docker run -d -p 8000:8000 -p 5173:5173 ${{ secrets.DOCKER_USERNAME }}/diagnobot:${{ inputs.WORKSPACE }}
